from __future__ import annotations

import json
from pathlib import Path
from typing import Annotated

import typer
from rich.table import Table

from rageval.cli._console import console
from rageval.core.config import PipelineConfig
from rageval.core.llm import MockLLMClient, create_llm_client
from rageval.evaluators.claim_extraction import extract_claims_for_item
from rageval.storage.duckdb_dao import (
    delete_claims_for_item,
    get_claim_count_for_run,
    get_connection,
    get_run_by_id,
    get_run_items_for_evaluation,
    insert_extracted_claims,
)

# Task-specific mock response for dev/test mode.
# Returns two claims so `rageval extract-claims` produces meaningful output
# when judge.provider == "mock", instead of all-unknown results.
_MOCK_JUDGE_RESPONSE = json.dumps({
    "claims": [
        "The answer addresses the question.",
        "The response is generated by a mock model.",
    ]
})


def _build_judge_client(judge_config):
    """Build the judge LLM client.

    When ``provider == "mock"``, returns a :class:`MockLLMClient` pre-loaded
    with claim-extraction JSON for meaningful dev output.
    """
    if judge_config.provider == "mock":
        return MockLLMClient(response_text=_MOCK_JUDGE_RESPONSE, model=judge_config.model)
    return create_llm_client(judge_config)


def extract_claims(
    run: Annotated[str, typer.Option("--run", "-r", help="Run ID to process")],
    config: Annotated[str, typer.Option("--config", "-c", help="Pipeline config YAML")] = "configs/baseline.yaml",
) -> None:
    """Decompose generated answers into atomic claims and store in DuckDB."""
    project_dir = Path.cwd()

    if not (project_dir / ".rageval").exists():
        console.print(
            "[red]Error:[/red] .rageval/ not found.\n"
            "  Run [bold]rageval init[/bold] first."
        )
        raise typer.Exit(1)

    config_path = project_dir / config
    if not config_path.exists():
        console.print(f"[red]Error:[/red] Config file not found: {config_path}")
        raise typer.Exit(1)

    try:
        pipeline_config = PipelineConfig.from_yaml(config_path)
    except Exception as exc:
        console.print(f"[red]Error loading config:[/red] {exc}")
        raise typer.Exit(1)

    llm_client = _build_judge_client(pipeline_config.judge)

    db_path = project_dir / ".rageval" / "runs.db"
    con = get_connection(db_path)

    try:
        run_row = get_run_by_id(con, run)
        if run_row is None:
            console.print(f"[red]Error:[/red] Run not found: {run!r}")
            raise typer.Exit(1)

        items = get_run_items_for_evaluation(con, run)
        if not items:
            console.print("[yellow]No run items found for this run.[/yellow]")
            return

        total_claims = 0
        unknown_count = 0

        for item in items:
            result = extract_claims_for_item(
                generated_answer=item["generated_answer"],
                llm_client=llm_client,
            )
            # Idempotent: delete existing claims before inserting new ones
            delete_claims_for_item(con, item["item_id"])
            insert_extracted_claims(con, item["item_id"], result.claims)
            total_claims += len(result.claims)
            if result.label == "unknown":
                unknown_count += 1

    finally:
        con.close()

    n_total = len(items)

    table = Table(title="Claim Extraction Summary", show_header=True)
    table.add_column("Field", style="bold")
    table.add_column("Value", justify="right")
    table.add_row("Run ID", run[:16] + "...")
    table.add_row("Judge model", pipeline_config.judge.model)
    table.add_row("Items processed", str(n_total))
    table.add_row("Total claims extracted", str(total_claims))
    table.add_row("Unknown (judge failures)", str(unknown_count))
    console.print(table)
